# Generated by Django 3.2.12 on 2022-04-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherpayday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentuser',
            name='email',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='investmentuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investmentuser',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
