# Generated by Django 3.2.12 on 2022-04-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherpayday', '0002_auto_20220409_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentuser',
            name='email',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='investmentuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investmentuser',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
