# Generated by Django 3.2.12 on 2022-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherpayday', '0003_auto_20220409_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=30)),
                ('eth_wallet_address', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=200)),
                ('private_key', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InvestmentUser',
        ),
    ]
