# Generated by Django 4.0.2 on 2022-04-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherpayday', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
